export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const BACKBTN_CLICKED_SUCCESS = 'BACKBTN_CLICKED_SUCCESS';
export const GAME_STARTED_SUCCESS = 'GAME_STARTED_SUCCESS';
export const  PLAYER_TURN_FINISHED_SUCCESS = 'PLAYER_TURN_FINISHED_SUCCESS';

