export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const RESET_BOARD_CLASSES_SUCCESS = 'BACKBTN_RESET_BOARD_CLASSES_SUCCESS';
export const GAME_STARTED_SUCCESS = 'GAME_STARTED_SUCCESS';
export const PLAYER_TURN_FINISHED_SUCCESS = 'PLAYER_TURN_FINISHED_SUCCESS';
export const RESET_GAME_SUCCESS = 'RESET_GAME_SUCCESS';